version: '3.8'

services:
  app:
    build: .
    network_mode: host
    container_name: app-mv
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-mv
    restart: always
    command: ["--default-authentication-plugin=mysql_native_password" , "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci",]
    env_file:
      - ./.docker/config/db.env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    cap_add:
      - SYS_NICE # desabilitar o aviso "mbind : Operation not permitted"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
      #- "./.docker/config/db-custon.cnf:/etc/mysql/conf.d/custom.cnf"

  adminer:
    image: adminer:4
    container_name: adm-db-mv
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
